window:
  decorations: none

  dimensions:
    columns: 120
    lines: 30

  padding:
    x: 10
    y: 10

font:
  size: 10

  normal:
    family: JetBrains Mono
    style: Regular

  bold:
    family: JetBrains Mono
    style: Bold

  italic:
    family: JetBrains Mono
    style: Italic

  bold_italic:
    family: JetBrains Mono
    style: Bold Italic

draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: '#000000'
    foreground: '#FBF1C7'

  normal:
    black:   '#282828'
    red:     '#CC241D'
    green:   '#98971A'
    yellow:  '#D79921'
    blue:    '#458588'
    magenta: '#B16286'
    cyan:    '#689D6A'
    white:   '#A89984'

  bright:
    black:   '#928374'
    red:     '#FB4934'
    green:   '#B8BB26'
    yellow:  '#FABD2F'
    blue:    '#83A598'
    magenta: '#D3869B'
    cyan:    '#8EC07C'
    white:   '#EBDBB2'
